version: '3.9'

services:
  weaviate:
    image: semitechnologies/weaviate:1.28.4
    ports:
      - 8080:8080
      - 50051:50051
    restart: on-failure:0
    volumes:
      - ./weaviate-data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      BACKUP_FILESYSTEM_PATH: '/var/lib/weaviate/backups'
      ENABLE_API_BASED_MODULES: 'true'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-huggingface'
      ENABLE_MODULES: 'text2vec-huggingface,qna-huggingface,backup-filesystem'
      HUGGINGFACE_API_KEY: ${HF_SERVERLESS_INFERENCE_TOKEN}
      # Add this to disable cluster mode and prevent joining attempts
      CLUSTER_HOSTNAME: 'node1'
      # Disable peer-to-peer communication attempts
      DISABLE_AUTHENTICATION: 'true'
      # Specify a single node setup
      CLUSTER_GOSSIP_BIND_PORT: '0'
      # Explicitly set standalone mode
      PERSISTENCE_LSM_ACCESS_STRATEGY: 'file'
      ASYNC_INDEXING: 'true'
      # Increase disk threshold to prevent warnings
      DISK_USE_WARNING_PERCENTAGE: '90'
      DISK_USE_READONLY_PERCENTAGE: '95'
    # Use a simpler healthcheck that just checks the HTTP endpoint
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/meta"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - rag-network

  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./audio_files:/app/audio_files
      - ./transcripts:/app/transcripts
      - ./main.py:/app/main.py
      - ./src:/app/src
    depends_on:
      weaviate:
        condition: service_started
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_SERVERLESS_INFERENCE_TOKEN=${HF_SERVERLESS_INFERENCE_TOKEN}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - YOUTUBE_PLAYLIST_URL=${YOUTUBE_PLAYLIST_URL}
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
    networks:
      - rag-network
    restart: unless-stopped

networks:
  rag-network:
    driver: bridge